name: Tests and Coverage

on:
  workflow_run:
    workflows: ["Check Black & Pylint"]
    types:
      - completed
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'pull_request' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Run tests with Docker Compose
        run: |
          # Create a directory for coverage data
          mkdir -p coverage
          chmod 777 coverage
          
          # Run tests with Docker Compose
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from app-test
          
          # Check if coverage.xml exists
          if [ ! -f coverage/coverage.xml ]; then
            echo "Coverage file not found!"
            exit 1
          fi
      
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/coverage.xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage.xml
          fail_ci_if_error: false
      
      - name: Clean up Docker resources
        if: always()
        run: docker-compose -f docker-compose.test.yml down -v 